### ISSUE TITLE
service may need esapi

### ISSUE THREAD

**Issue by lushijie** [weihongyu12/think-esapi#1]
Esapi shoud be also as a extend of service. Welcome to pull request to [think-awesome](https://github.com/thinkjs/think-awesome).

**Comment by weihongyu12** [comment]
Yes, this is a good idea, I have pull request to think-awesome, please merge

**Comment by lushijie** [comment]
Before accepting  the pull request, I think the library should do some modifies:

// 1. index.js
```js
module.exports = {
  controller: {
    esapi: new ESAPI()
  },
  // inject for service
  service: {
     esapit: new ESAPI()
  }, 
  context: {
    esapi: new ESAPI()
  },
  think: {
    esapi: new ESAPI()
  }
};
```
// 2. README.md
https://img.shields.io/npm/v/think-esapi..svg.  One more dot is written, it should be .svg.

// 3.Test Coveralls
I see you have written the test case, if a coveralls icon link is added to readme.md would be better.

**Comment by weihongyu12** [comment]
OK, I accepted your suggestion and modified the code and documentation.
but my code is written like this
// index.js
```javascript
module.exports = {
  controller: {
    esapi: new ESAPI()
  },
  // inject for service, the name is `esapi` instead of `esapit`
  service: {
    esapi: new ESAPI()
  },
  context: {
    esapi: new ESAPI()
  },
  think: {
    esapi: new ESAPI()
  }
};
```
Can help me explain why use the service?

**Comment by lushijie** [comment]
Sometime we may encoder the chars  in service.

**Comment by weihongyu12** [comment]
Thanks for your guidance, now the project has been merged
